# Generated by Django 6.1 on 2026-08-19 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('business_hotel', 'Business Hotel'), ('resort', 'Resort'), ('boutique', 'Boutique Hotel'), ('budget', 'Budget Hotel'), ('heritage', 'Heritage Property'), ('serviced_apartments', 'Serviced Apartments')], max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rooms', models.PositiveIntegerField()),
                ('property_area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated, e.g. Pool, Gym, Restaurant, Parking, Wi-Fi')),
                ('operational_status', models.CharField(choices=[('operational', 'Operational'), ('under_renovation', 'Under Renovation'), ('closed', 'Closed')], default='operational', max_length=20)),
                ('years_in_operation', models.PositiveIntegerField(default=0)),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('management_contract', 'Management Contract')], default='freehold', max_length=20)),
                ('asking_amount', models.DecimalField(decimal_places=2, help_text='Expected lease / asking amount', max_digits=14)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lease_duration_years', models.PositiveIntegerField(blank=True, null=True)),
                ('renewal_terms', models.CharField(blank=True, max_length=255)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Sample/mock financial data', max_digits=14, null=True)),
                ('annual_occupancy_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage, sample data', max_digits=5, null=True)),
                ('contact_preference', models.CharField(choices=[('platform_message', 'Platform Messaging Only'), ('phone', 'Phone'), ('email', 'Email')], default='platform_message', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.hotellisting')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='listings.hotellisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('buyer', 'listing')},
            },
        ),
    ]
